name: Build and Error Tracking

on:
  push:
    branches:
      - staging

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10  # Stop the job after 10 minutes, adjust as needed

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pygame

      - name: Run Pygame server
        id: run_server
        run: |
          # Run server script and capture any errors
          python server.py > output.log 2>&1 || echo "Error occurred in server.py" >> error.log

      - name: Check for errors
        run: |
          # If error.log contains an error, send it in the email
          if grep -q "Error occurred in server.py" error.log; then
            echo "Error detected. Capturing full error output..."
            cat output.log >> error_output.log  # Save the full output to a new file
            echo "ERROR_OCCURRED=true" >> $GITHUB_ENV
          else
            echo "No error detected. Proceeding with job."
            echo "ERROR_OCCURRED=false" >> $GITHUB_ENV
          fi

      - name: Find responsible developer
        if: env.ERROR_OCCURRED == 'true'
        run: |
          AUTHOR=$(git blame -L $ERROR_LINE,$ERROR_LINE -- $ERROR_FILE | awk '{print $2}')
          AUTHOR_EMAIL=$(git log -1 --format='%ae' -s $AUTHOR)
          echo "Author: $AUTHOR ($AUTHOR_EMAIL)"
          echo "AUTHOR_EMAIL=$AUTHOR_EMAIL" >> $GITHUB_ENV

      - name: Send Email Notification
        if: env.ERROR_OCCURRED == 'true'
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.mail.me.com  # iCloud SMTP server
          server_port: 587  # Use 465 for SSL if you prefer
          username: ${{ secrets.EMAIL_USERNAME }}  # Your iCloud email address
          password: ${{ secrets.EMAIL_PASSWORD }}  # Your iCloud App Password
          subject: "Build Failed - You introduced an error!"
          to: ${{ env.AUTHOR_EMAIL }}
          body: |
            Your commit caused the following error during the build process:
            $(cat error_output.log)  # Use the content of the error_output.log file
          from: "GitHub Actions Bot"
